# Build umb-hostagent: the -javaagent that materialises 1.7.10 snapshot content as native
# Minecraft 26.2 blocks/items/tabs, plus dev.umb.packgen.PackGen.
#
#   powershell -NoProfile -ExecutionPolicy Bypass -File tools\build-hostagent.ps1
#
# Compiles on JDK 25 ONLY (research\jars\26.2\client.jar is classfile major 69).
# gson is compiled against the EXACT jar that is on the game classpath.
# ASM (asm, asm-tree, asm-commons - BSD 3-clause) is bundled into the agent jar because the
# game classpath ships no ASM at all; there is nothing to collide with, so the classes keep
# their org.objectweb.asm package (bundled, not relocated).
$ErrorActionPreference = 'Stop'

$repo = Split-Path -Parent $PSScriptRoot
$jdk25 = Join-Path $repo 'tools\jdk-25.0.4.1+1\bin'
$jdk21 = Join-Path $repo 'tools\jdk-21.0.12.1+1\bin'
$javac = Join-Path $jdk25 'javac.exe'
$javac21 = Join-Path $jdk21 'javac.exe'
$jar = Join-Path $jdk25 'jar.exe'
$client = Join-Path $repo 'research\jars\26.2\client.jar'
$cpFile = Join-Path $repo 'research\visual\mc262-vanilla\classpath.txt'
$src = Join-Path $repo 'umb-hostagent\src\main\java'
$build = Join-Path $repo 'build\hostagent'
$classes = Join-Path $build 'classes'
$stage = Join-Path $build 'stage'
$outJar = Join-Path $build 'umb-hostagent.jar'

foreach ($p in @($javac, $jar, $client, $cpFile)) {
  if (-not (Test-Path $p)) { Write-Error ("missing: " + $p); exit 1 }
}

# ---- G2 task 1: the bridge-api mirror is a BUILD-TIME COPY of Lane A's canonical source, never a
# hand-maintained duplicate. Overwritten on every build so the two copies can never drift; the
# byte-for-byte class-file gate below still runs as a belt-and-suspenders check (e.g. it would
# catch a stale build/legacy/umb-bridge-api.jar built from an older canonical source).
$canonicalApiDir = Join-Path $repo 'umb-legacy\src\bridge-api\java\dev\umb\bridge\api'
$mirrorApiDir = Join-Path $repo 'umb-hostagent\src\main\java\dev\umb\bridge\api'
if (-not (Test-Path $canonicalApiDir)) { Write-Error ("missing canonical umb-bridge-api source: " + $canonicalApiDir); exit 1 }
New-Item -ItemType Directory -Force $mirrorApiDir | Out-Null
$mirrorHeader = @(
  '// MIRROR of the canonical umb-bridge-api owned by Lane A (umb-legacy) -- do not hand-edit.',
  '// Synced verbatim by tools/build-hostagent.ps1 from',
  '// umb-legacy/src/bridge-api/java/dev/umb/bridge/api/ on every build. If you need to change the',
  '// boundary contract, change it there (and change BOTH sides together per DESIGN.md).',
  ''
) -join "`n"
$syncedCount = 0
Get-ChildItem -Filter *.java $canonicalApiDir | ForEach-Object {
  $canonicalText = Get-Content -Raw $_.FullName
  # Append the mirror header AFTER the whole compilation unit (trailing comment, valid Java) rather
  # than inserting it before the code: inserting lines ABOVE the class body would shift every
  # LineNumberTable entry javac emits for it, making the byte-identity gate below fail for any
  # class with actual method bodies even though nothing semantically changed (SlotData/StackData
  # hit exactly this during development - see g2-integration-progress.md).
  $mirrored = $canonicalText.TrimEnd() + "`n`n" + $mirrorHeader
  [System.IO.File]::WriteAllText((Join-Path $mirrorApiDir $_.Name), $mirrored, (New-Object System.Text.UTF8Encoding $false))
  $syncedCount++
}
Write-Output ("synced bridge-api mirror: " + $syncedCount + " files from canonical source")

# the exact gson the game runs with.  The shared classpath artifact is generated by the
# Linux-side visual tooling and is therefore colon-separated with /mnt/<drive>/ paths;
# javac.exe on Windows needs native paths and semicolon separators.  Keep accepting a
# native Windows classpath too so the build remains portable across the two runners.
$rawGameCp = (Get-Content $cpFile -Raw).Trim()
$gameCpParts = $rawGameCp -split ';'
if ($gameCpParts.Count -eq 1 -and $rawGameCp -match '/mnt/[A-Za-z]/') {
  $gameCpParts = $rawGameCp -split ':'
}
$gameCp = (($gameCpParts | ForEach-Object {
  $entry = $_
  if ($entry -match '^/mnt/([A-Za-z])/(.*)$') {
    $entry = ($matches[1].ToUpper() + ':\' + ($matches[2] -replace '/', '\'))
  }
  $entry
}) -join ';')
$gson = ($gameCp -split ';' | Where-Object { $_ -match 'gson' } | Select-Object -First 1)
if (-not $gson) { Write-Error 'no gson on the game classpath'; exit 1 }
Write-Output ("gson  : " + $gson)

$asm = @(
  (Join-Path $repo 'tools\junit\asm-9.9.jar'),
  (Join-Path $repo 'tools\junit\asm-tree-9.9.jar'),
  (Join-Path $repo 'tools\junit\asm-commons-9.9.jar')
)
foreach ($a in $asm) { if (-not (Test-Path $a)) { Write-Error ("missing asm jar: " + $a); exit 1 } }

# G2 task 2: UmbUniverse embeds the legacy universe's own loader hierarchy (dev.umb.legacy.boot.*
# + net.minecraft.launchwrapper.* + jopt-simple, tier 1 in its javadoc). These 4 jars carry no
# package that can collide with anything on the 26.2 classpath (verified: no
# net.minecraft.launchwrapper / joptsimple / dev.umb.legacy.* in client.jar), so unlike log4j
# (isolated at RUNTIME by UmbUniverse's UniverseRootLoader, see its javadoc) they are bundled
# straight into umb-hostagent.jar alongside ASM.
$legacyBuild = Join-Path $repo 'build\legacy'
$umbLegacyBootJar = Join-Path $legacyBuild 'umb-legacy-boot.jar'
$umbLegacyApiJar = Join-Path $legacyBuild 'umb-legacy-api.jar'
$umbBridgeApiCanonicalJar = Join-Path $legacyBuild 'umb-bridge-api.jar'
$libsDir = Join-Path $repo 'research\visual\mc1710-native\libraries'
$launchwrapperJar = Join-Path $libsDir 'net\minecraft\launchwrapper\1.12\launchwrapper-1.12.jar'
$joptJar = (Get-ChildItem -Recurse -Filter 'jopt-simple-*.jar' $libsDir | Select-Object -First 1).FullName
$tier1Jars = @($umbLegacyBootJar, $umbLegacyApiJar, $launchwrapperJar, $joptJar)
foreach ($j in $tier1Jars) {
  if (-not $j -or -not (Test-Path $j)) { Write-Error ("missing tier-1 jar (run tools\build-legacy.ps1 first): " + $j); exit 1 }
}
if (-not (Test-Path $umbBridgeApiCanonicalJar)) { Write-Error ("missing canonical jar (run tools\build-legacy.ps1 first): " + $umbBridgeApiCanonicalJar); exit 1 }

if (Test-Path $classes) { Remove-Item -Recurse -Force $classes }
if (Test-Path $stage) { Remove-Item -Recurse -Force $stage }
New-Item -ItemType Directory -Force $classes | Out-Null
New-Item -ItemType Directory -Force $stage | Out-Null

# compile the (freshly synced) bridge-api mirror FIRST, with jdk21's javac at --release 8, no
# classpath - IDENTICAL invocation shape to build-legacy.ps1's
# `Compile 'bridge-api' ... '' '8' ...` step, so the output is byte-identical to the canonical jar
# modulo the mirror header COMMENT (comments are stripped before bytecode generation, so they
# cannot affect the class file). Compiled separately, rather than folded into the main -source 21
# compile below, because a single -source 21 compile of the same files would legitimately produce
# DIFFERENT bytecode (different classfile major version, different debug-info defaults) - not a
# real divergence, just two compilers targeting two releases, but it would make the byte-identity
# gate below meaningless.
$bridgeApiMirrorClasses = Join-Path $build 'classes-bridge-api-mirror'
if (Test-Path $bridgeApiMirrorClasses) { Remove-Item -Recurse -Force $bridgeApiMirrorClasses }
New-Item -ItemType Directory -Force $bridgeApiMirrorClasses | Out-Null
$mirrorSources = Get-ChildItem -Filter *.java $mirrorApiDir | ForEach-Object { $_.FullName }
$mirrorArgfile = Join-Path $build 'javac-bridge-api-mirror.args'
($mirrorSources | ForEach-Object { '"' + ($_ -replace '\\', '\\\\') + '"' }) -join "`n" | Out-File $mirrorArgfile -Encoding ascii
& $javac21 -nowarn -encoding UTF-8 --release 8 -d $bridgeApiMirrorClasses ('@' + $mirrorArgfile)
if ($LASTEXITCODE -ne 0) { Write-Error 'bridge-api mirror javac failed'; exit 1 }
Write-Output 'compiled bridge-api mirror (release 8, matching Lane A exactly)'

# compile against the FULL game classpath (dfu/brigadier/guava are needed to see MC signatures) + ASM
# + the tier-1 legacy jars (UmbUniverse imports LegacyLoader/LegacyClasspath/Launch directly) + the
# just-compiled bridge-api mirror (main code implements/references dev.umb.bridge.api directly).
# LaunchWrapper is compile-only here: release users receive the official jar from umb-installer,
# and HostAgent appends that verified jar to the application classloader at premain.
$compileCp = ((@($gameCp) + $asm + $tier1Jars + @($bridgeApiMirrorClasses)) -join ';')
$sources = Get-ChildItem -Recurse -Filter *.java $src | ForEach-Object { $_.FullName } |
  Where-Object { $_ -notlike '*\dev\umb\bridge\api\*' }
Write-Output ("sources: " + $sources.Count + " (+ 7 bridge-api mirror sources compiled separately above)")

$argfile = Join-Path $build 'javac-main.args'
($sources | ForEach-Object { '"' + ($_ -replace '\\', '\\\\') + '"' }) -join "`n" | Out-File $argfile -Encoding ascii
& $javac -nowarn -encoding UTF-8 -source 21 -target 21 -cp $compileCp -d $classes ('@' + $argfile)
if ($LASTEXITCODE -ne 0) { Write-Error 'javac failed'; exit 1 }
Write-Output 'compiled main'

New-Item -ItemType Directory -Force (Join-Path $classes 'dev\umb\bridge\api') | Out-Null
Copy-Item -Force (Join-Path $bridgeApiMirrorClasses 'dev\umb\bridge\api\*.class') (Join-Path $classes 'dev\umb\bridge\api')

# ---- G2 task 1 GATE: the mirror's COMPILED class files must be byte-identical to Lane A's
# canonical umb-bridge-api.jar. Source-level sync (above) makes this true by construction, but the
# gate still runs so a stale/hand-edited canonical jar, or a future refactor that breaks the sync
# step, fails the BUILD immediately instead of surfacing as a silent classloading mismatch at
# 26.2-embedding time.
$gateDir = Join-Path $build 'bridge-api-canonical-check'
if (Test-Path $gateDir) { Remove-Item -Recurse -Force $gateDir }
New-Item -ItemType Directory -Force $gateDir | Out-Null
Push-Location $gateDir
& $jar --extract --file $umbBridgeApiCanonicalJar
Pop-Location
$mirrorClassesDir = Join-Path $classes 'dev\umb\bridge\api'
$canonicalClassesDir = Join-Path $gateDir 'dev\umb\bridge\api'
$mismatches = @()
$mirrorClasses = Get-ChildItem -Filter *.class $mirrorClassesDir | Sort-Object Name
if ($mirrorClasses.Count -eq 0) { Write-Error 'bridge-api mirror produced no .class files'; exit 1 }
foreach ($mc in $mirrorClasses) {
  $canonicalFile = Join-Path $canonicalClassesDir $mc.Name
  if (-not (Test-Path $canonicalFile)) { $mismatches += ($mc.Name + ' : missing from canonical jar'); continue }
  $h1 = (Get-FileHash -Algorithm SHA256 $mc.FullName).Hash
  $h2 = (Get-FileHash -Algorithm SHA256 $canonicalFile).Hash
  if ($h1 -ne $h2) { $mismatches += ($mc.Name + ' : SHA256 differs from canonical (' + $h1 + ' vs ' + $h2 + ')') }
}
if ($mismatches.Count -gt 0) {
  Write-Error ("BRIDGE-API-MIRROR-MISMATCH: " + $mismatches.Count + " class(es) differ from build\legacy\umb-bridge-api.jar:`n  " + ($mismatches -join "`n  "))
  exit 1
}
Write-Output ("BRIDGE-API-MIRROR-OK: " + $mirrorClasses.Count + " class files byte-identical to canonical umb-bridge-api.jar")

# stage our classes, then bundle ASM + our tier-1 legacy loader jars on top. LaunchWrapper is
# deliberately excluded; it is Mojang code and is installed from the official library server.
Copy-Item -Recurse -Force (Join-Path $classes '*') $stage
foreach ($a in ($asm + @($umbLegacyBootJar, $umbLegacyApiJar, $joptJar))) {
  Push-Location $stage
  & $jar --extract --file $a
  Pop-Location
}
Remove-Item -Recurse -Force (Join-Path $stage 'META-INF') -ErrorAction SilentlyContinue
Remove-Item -Recurse -Force (Join-Path $stage 'module-info.class') -ErrorAction SilentlyContinue

$manifest = Join-Path $build 'MANIFEST.MF'
@(
  'Manifest-Version: 1.0',
  'Premain-Class: dev.umb.hostagent.HostAgent',
  'Agent-Class: dev.umb.hostagent.HostAgent',
  'Can-Retransform-Classes: true',
  'Implementation-Title: umb-hostagent',
  'Implementation-Vendor: UniversalModBridge',
  ''
) -join "`n" | Out-File $manifest -Encoding ascii

$jarOutput = $outJar
if (Test-Path $outJar) {
  try {
    Remove-Item -Force $outJar -ErrorAction Stop
  } catch {
    # A live Minecraft process may have the currently deployed agent open.  Never stop it
    # or overwrite a locked artifact: finish the build into a uniquely named jar instead.
    $stamp = Get-Date -Format 'yyyyMMdd-HHmmss'
    $jarOutput = Join-Path $build ('umb-hostagent-built-' + $stamp + '.jar')
    Write-Warning ('existing jar is locked; preserving it and writing: ' + $jarOutput)
  }
}
& $jar --create --file $jarOutput --manifest $manifest -C $stage .
if ($LASTEXITCODE -ne 0) { Write-Error 'jar failed'; exit 1 }

# probe classes stay OUT of the agent jar so the agent jar is only the seam
Write-Output ''
Write-Output ('JAR: ' + $jarOutput + '  bytes=' + (Get-Item $jarOutput).Length)
Write-Output '--- manifest ---'
& $jar --file $jarOutput --describe-module 2>$null | Out-Null
$entries = (& $jar --list --file $jarOutput)
Write-Output ('entries: ' + $entries.Count)
Write-Output '--- dev/umb entries ---'
$entries | Where-Object { $_ -like 'dev/umb/*' -and $_ -like '*.class' } | Sort-Object | ForEach-Object { Write-Output ('  ' + $_) }
Write-Output ('--- bundled asm classes: ' + ($entries | Where-Object { $_ -like 'org/objectweb/asm/*.class' }).Count + ' ---')
$entries | Where-Object { $_ -like 'org/objectweb/asm/*' -and $_ -notlike '*.class' } | Sort-Object | ForEach-Object { Write-Output ('  ' + $_) }
